### ISSUE TITLE
Choose a better name for the library

### ISSUE THREAD

**Issue by aminya** [atom-community/zadeh#51]
fuzzaldrin-plus-fast is exceedingly long, and it is not catchy at all. We should choose a better name for this library that is catchy and unique. 

We don't have to follow the historical reasons for naming. The name should be independent of Atom, as this library can be directly used from C++ or other environments.

**Comment by DeeDeeG** [comment]
- ~~Tribble - the fuzzy creature from Star Trek~~ This (exact) name is taken
- Great Filter - a theory to do with life in the universe (this library filters possible results and picks the best ones... space theme calls back to Buzz Aldrin)
- Armstrong - another astronaut from the Apollo 11 mission, just like Buzz Aldrin
- [Something about rockets? Because this library is fast...]
- Schrodinger - quantum superpositions = "uncertain" to predict, which is kind of like fuzzy logic... and cats are fuzzy (Schrodinger's cat). Quantum mechanics relate to quarks, which continues the "Atom" theme.
- Heisenberg - referencing the "uncertainty principle" and inexact measurements
- Cheetah - fast and fuzzy

**Comment by aminya** [comment]
Your suggestions reminded me of [Zadeh](https://en.wikipedia.org/wiki/Lotfi_A._Zadeh), the inventor of fuzzy logic!

In Persian, the full name is `Lotfi Aliasker Zadeh`, but in English, he was called `Zadeh` for short.
